project_id = "wgpqsmoblkkrlaymmdba"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "1h"
secure_password_change = true

[edge_runtime]
enabled = true
port = 54321
inspector_port = 8083

[functions.enhance-message]
verify_jwt = true

[functions.kiwify-webhook]
verify_jwt = false

[functions.evolution-create-instance]
verify_jwt = true

[functions.evolution-check-status]
verify_jwt = true

[functions.evolution-fetch-groups]
verify_jwt = true

[functions.evolution-delete-instance]
verify_jwt = true

[functions.evolution-send-message]
verify_jwt = true

[functions.evolution-reconnect-instance]
verify_jwt = true

[functions.evolution-fetch-group-participants]
verify_jwt = true

[functions.evolution-update-group-settings]
verify_jwt = true

[functions.evolution-update-group-subject]
verify_jwt = true

[functions.evolution-update-group-picture]
verify_jwt = true

[functions.evolution-update-group-description]
verify_jwt = true

[functions.extract-contacts]
verify_jwt = true

[functions.analyze-engagement]
verify_jwt = true

[functions.analyze-trends]
verify_jwt = true

[functions.create-campaign]
verify_jwt = true

[functions.redirect-link]
verify_jwt = false

[functions.suggest-offer-text]
verify_jwt = true

[functions.generate-offer-post-image]
verify_jwt = false